apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s

    scrape_configs:
      - job_name: 'users-api'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['users-api:80']
            labels:
              application: 'UsersAPI'

      - job_name: 'catalog-api'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['catalog-api:80']
            labels:
              application: 'CatalogAPI'

      - job_name: 'payments-api'
        metrics_path: '/metrics'
        static_configs:
          - targets: ['payments-api:80']
            labels:
              application: 'PaymentsAPI'

      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
