apiVersion: v1
kind: ConfigMap
metadata:
  name: kong-gateway-config
data:
  kong.yml.template: |
    _format_version: "3.0"
    _transform: true

    consumers:
      - username: users-api
        jwt_secrets:
          - key: UsersAPI
            algorithm: HS256
            secret: "__JWT_KEY__"

    services:
      - name: users-api
        url: http://users-api:80
        routes:
          - name: users-auth
            paths:
              - /api/auth
            strip_path: false

      - name: catalog-api
        url: http://catalog-api:80
        routes:
          - name: catalog-games-read
            paths:
              - /api/games
            methods:
              - GET
            strip_path: false
          - name: catalog-games-write
            paths:
              - /api/games
            methods:
              - POST
              - PUT
              - DELETE
            strip_path: false
            plugins:
              - name: jwt
                config:
                  claims_to_verify:
                    - exp
          - name: catalog-library
            paths:
              - /api/library
            strip_path: false
            plugins:
              - name: jwt
                config:
                  claims_to_verify:
                    - exp
